// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Concoct_Builder
{
    public partial class ConcoctbuilderDbContext : DbContext
    {
        public ConcoctbuilderDbContext()
        { 
        }

        public ConcoctbuilderDbContext(DbContextOptions<ConcoctbuilderDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<LayoutData> LayoutData { get; set; }
        public virtual DbSet<Layouts> Layouts { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlite("Data Source=ConcoctBuilder.db");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<LayoutData>(entity =>
            {
                entity.HasOne(d => d.Layout)
                    .WithMany(p => p.LayoutData)
                    .HasForeignKey(d => d.LayoutId);
            });

            modelBuilder.Entity<Layouts>(entity =>
            {
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}