// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Concoct_Builder
{
    public partial class ConcoctbuilderDbContext : DbContext
    {
        public ConcoctbuilderDbContext()
        {
            Database.EnsureCreated();
        }

        public ConcoctbuilderDbContext(DbContextOptions<ConcoctbuilderDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<LayoutData> LayoutData { get; set; }
        public virtual DbSet<Layouts> Layouts { get; set; }
        public virtual DbSet<UserSettings> UserSettings { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<LayoutData>(entity =>
            {
                entity.HasOne(d => d.Layout)
                    .WithMany(p => p.LayoutData)
                    .HasForeignKey(d => d.LayoutId);
            });

            modelBuilder.Entity<Layouts>(entity =>
            {
                entity.HasOne(d => d.UserSettingNavigation)
                    .WithMany(p => p.Layouts)
                    .HasForeignKey(d => d.UserSetting);
            });

            modelBuilder.Entity<UserSettings>(entity =>
            {
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}