// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Concoct_Builder
{
    public partial class Layouts
    {
        public Layouts()
        {
            LayoutData = new HashSet<LayoutData>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public string CreatedAt { get; set; }
        public string UpdatedAt { get; set; }
        public string Owner { get; set; }

        public virtual ICollection<LayoutData> LayoutData { get; set; }
    }
}