// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Concoct_Builder
{
    public partial class UserSettings
    {
        public UserSettings()
        {
            Layouts = new HashSet<Layouts>();
        }

        public long Id { get; set; }
        public long? ConnectionType { get; set; }
        public string Endpoint { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Key { get; set; }
        public string InstanceAddress { get; set; }
        public string OrganizationName { get; set; }
        public long? IsActive { get; set; }

        public virtual ICollection<Layouts> Layouts { get; set; }
    }
}